### ISSUE TITLE
epoch stale after mainchain rpc massive restart

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2559] opened 2023-09-08 10:50 UTC
to reproduce: stop all mainchain rpc (for upgrade for exmaple), then start

workaround: restart all ir nodes

**Comment by roman-khimov** [comment] 2023-12-15 20:30
Container can't be created as well in this case until all nodes are restarted.

**Comment by carpawell** [comment] 2023-12-18 09:11
> stop all mainchain rpc

@532910, how long RPCs were down? Seconds? Minutes?

> until all nodes are restarted

@roman-khimov, what exact nodes? IR? SN?

**Comment by 532910** [comment] 2023-12-18 09:15
> how long

let start with minutes

> what exact nodes? IR? SN?

IR, I believe

**Comment by carpawell** [comment] 2023-12-25 13:33
No progress for now: one node local consensus does not allow reproducing. The best I can do here is wait until the next update and see the logs/profiles. If that is unacceptable I may try the local 4/7 nodes consensus.

**Comment by roman-khimov** [comment] 2024-01-29 07:24
Can't be reproduced at this stage, waiting for another case in some network.

**Comment by roman-khimov** [comment] 2024-04-27 14:20
Seems to be reproducible if 2/3 RPC nodes to go offline for some time.

**Comment by evgeniiz321** [comment] 2024-08-05 19:27
Got a stable reproduction during new payment tests `tests.payment.test_container_payments.TestContainerPayments#test_container_payments`:  https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/477-1722817756/index.html#suites/44e11ced39071e8d0cfc11c5b94622ba/d3f9a85ef9ecb46a/.

**Comment by carpawell** [comment] 2024-09-27 14:28
@evgeniiz321, as I understand, in _your case_ you want to make the test be faster so you change epoch duration to 20 blocks, right? I do not see any epoch ticks after changing so it is impossible to change epoch duration immediately, we do not have notifications about config changes and cannot recalculate the next block for epoch handling. As I understand you wait for a new epoch no longer than 60 seconds, probably, a new epoch will not happen if you used 240-second epoch before (1-second block for the default 240 epoch duration). Can you either try to tick epoch after network setting tuning or increase max awaiting to 240?

**Comment by carpawell** [comment] 2024-11-11 10:23
We have not seen this exact issue for so long so I close it, it can be reopened once it happens at least once.

**Comment by carpawell** [comment] 2024-12-04 16:59
Still was not the case. See https://github.com/nspcc-dev/neofs-node/issues/3007, it is more related to the situation.

**Closed by carpawell** 2024-12-04 16:59 UTC
Labels: bug, neofs-ir, blocked, U2, S4, I4
