### ISSUE TITLE
neofs error: chain/client: contract execution finished with state FAULT; exception: at instruction 3047 (THROW): unhandled exception: "invalid epoch"

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#2114] opened 2022-11-29 20:42 UTC
Buckets creation has been unavailable due to issue below. IR service restarting restored the cluster to health state.

ноя 29 17:58:35 az neofs-ir[16125]: 2022-11-29T17:58:35.038Z        info        netmap/handlers.go:15        tick        {"type": "epoch"}
ноя 29 17:58:35 az neofs-ir[16125]: 2022-11-29T17:58:35.040Z        error        netmap/process_epoch.go:83        can't invoke netmap.NewEpoch        {"error": "could not invoke method (newEpoch): neofs error: chain/client: contract execution finished with state FAULT; exception: at instruction 3047 (THROW): unhandled exception: \"invalid epoch\""}

[Logs](https://drive.google.com/file/d/1MP5cXQGTUtqnFUsOyekVrT9qSSXmujE_/view?usp=share_link)

**Comment by acid-ant** [comment] 2022-12-13 13:24
Found following warnings before the error happened:
```
ноя 29 17:57:47 az neofs-ir[16125]: 2022-11-29T17:57:47.029Z        warn        event/listener.go:276        listener worker pool drained        {"chain": "morph", "capacity": 10}
ноя 29 17:57:47 az neofs-ir[16125]: 2022-11-29T17:57:47.029Z        warn        event/listener.go:276        listener worker pool drained        {"chain": "morph", "capacity": 10}
ноя 29 17:57:47 az neofs-ir[16125]: 2022-11-29T17:57:47.029Z        warn        event/listener.go:276        listener worker pool drained        {"chain": "morph", "capacity": 10}
ноя 29 17:57:47 az neofs-ir[16125]: 2022-11-29T17:57:47.030Z        warn        event/listener.go:276        listener worker pool drained        {"chain": "morph", "capacity": 10}
```
Timestamp for the error from issue `ноя 29 17:58:35`
@fyrchik can that be related to the issue?

**Comment by acid-ant** [comment] 2022-12-13 13:37
Moreover lot of following type of errors:
```
ноя 29 16:12:15 az neofs-ir[16125]: 2022-11-29T16:12:15.784Z        error        innerring/settlement.go:240        basic income: could not send transfer        {"sender": "NgJDLfMArHNGJxT7mYpP4pMJ3DwSvmP9vV", "recipient": "NL1H4he1ggRajT1ZVqn23zveMRaH9jDvfh", "amount (GASe-12)": "586597261904", "details": "414e03000000000000", "error": "could not invoke method (transferX): neofs error: chain/client: contract execution finished with state FAULT; exception: at instruction 1725 (THROW): unhandled exception: \"can't transfer assets\""}
```

**Comment by acid-ant** [comment] 2022-12-13 14:21
Also found lot of following errors on all ir nodes:
```
error        netmap/process_epoch.go:83        can't invoke netmap.NewEpoch        {"error": "could not invoke method (newEpoch): failed to submit notary request: Block or transaction validation failed. (-504) - fallback transaction is valid after deposit is unlocked: ValidUntilBlock is XXX, deposit lock expires at XXXX"}
```

**Comment by fyrchik** [comment] 2022-12-15 09:59
@acid-ant Maybe related to #1486 .

**Comment by acid-ant** [comment] 2022-12-20 09:24
Have discussed with @anatoly-bogatyrev, we are not able to reproduce this issue with latest changes. @fyrchik could you close it?

**Closed** 2022-12-21 07:52 UTC
Labels: bug, P2
