### ISSUE TITLE
Deleted object is displayed in the list of container object

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-node#2850] opened 2024-05-13 19:34 UTC
Issue container list:

```
NEOFS_CLI_PASSWORD=*** neofs-cli --rpc-endpoint st1.t5.fs.neo.org:8080 --wallet /home/runner/work/gh-push-to-neofs/gh-push-to-neofs/.//wallet.json container list-objects --cid CdrZca2ccQRcJyCw2DzBTgDsZ32xJ889RghXdMTfER7s
RC: 0
Traceback (most recent call last):
Output: 
...
5rPTQ9TFJ3JmD8WNbXqtsFQ8Tbq6z4gkGDohU8sbQhAs
...
```

Issue delete:

```
Exception: Command failed: NEOFS_CLI_PASSWORD=*** neofs-cli --rpc-endpoint st1.t5.fs.neo.org:8080 --wallet /home/runner/work/gh-push-to-neofs/gh-push-to-neofs/.//wallet.json object delete --cid CdrZca2ccQRcJyCw2DzBTgDsZ32xJ889RghXdMTfER7s --oid '5rPTQ9TFJ3JmD8WNbXqtsFQ8Tbq6z4gkGDohU8sbQhAs'
Error code: 1
Output: 
Stdout: 
Stderr: rpc error: remove object via client: status: code = 2052 message = object already removed
```

In logs:

```
May 13 19:15:11 titan1 neofs-node[31687]: 2024-05-13T19:15:11.952Z        error        util/log.go:10        object service error        {"node": "/dns4/st3.t5.fs.neo.org/tcp/8080", "request": "PUT", "error": "could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/st3.t5.fs.neo.org/tcp/8080]: finish object stream: status: code = 2052 message = object already removed"}
```

## Expected Behavior
If an object is marked as deleted it should not be displayed in the list of objects

## Current Behavior
Objects are shown in the list of objects even if they are already or partially deleted

## Steps to Reproduce (for bugs)
Reproduces regularly in this job - https://github.com/nspcc-dev/gh-push-to-neofs/actions/runs/9068652152/job/24916429579

Maybe related to https://github.com/nspcc-dev/neofs-node/issues/2376

**Comment by roman-khimov** [comment] 2024-05-13 19:35
Related to https://github.com/nspcc-dev/neofs-node/issues/2376. But I wasn't able to get this object from a list locally with `./bin/neofs-cli --rpc-endpoint st1.t5.fs.neo.org:8080 container list-objects --ttl 1 --cid CdrZca2ccQRcJyCw2DzBTgDsZ32xJ889RghXdMTfER7s` and alike.

**Comment by roman-khimov** [comment] 2024-05-13 20:18
NOBUG. It was caused by concurrent tests using the same container in https://github.com/nspcc-dev/gh-push-to-neofs/pull/24. Fixed with limited `max-parallel` for the job.

**Closed by roman-khimov** 2024-05-13 20:18 UTC
Labels: bug, U2, S4, I4
