### ISSUE TITLE
not valid UTF-8 strings in locodedb

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neofs-node#2637] opened 2023-11-07 12:13 UTC
The new locode db (https://service.unece.org/trade/locode/loc231csv.zip) contains not valid utf-8 symbols. But IR expects valid ones.  

## Possible Solution
preprocess ISO 3166 to valid utf-8 strings.

**Comment by carpawell** [comment] 2023-11-07 13:08
Have you found what exact record does not fit utf-8? It seems like they are trying to make ISO 3166 in uft-8 encoding.

**Comment by AliceInHunterland** [comment] 2023-11-07 15:55
> Have you found what exact record does not fit utf-8? It seems like they are trying to make ISO 3166 in uft-8 encoding.

there are lots of them in  2023-1 SubdivisionCodes.csv, for example:
```
"AL","05","Gjirokast�r","County"
"AL","06","Kor��","County"
"AL","07","Kuk�s","County"
"AL","08","Lezh�","County"
"AL","09","Dib�r","County"
"AL","10","Shkod�r","County"
"AL","11","Tiran�","County"
"AL","12","Vlor�","County"
```
and first I found it in 	`SubDiv: Stockholms län` in the netmap snapshot

**Comment by carpawell** [comment] 2023-11-07 16:55
So the problem is in the "long" description? That is strange. Seems like `SubdivisionCodes.csv` is the only file with encoding problems. But there is some UTF-8 version of it: https://github.com/datasets/un-locode.

**Comment by roman-khimov** [comment] 2023-11-07 20:15
It's about the same issue as nspcc-dev/locode-db#1 to me. With the same solution --- sanitize inputs, add fixes for known problems.

**Comment by AliceInHunterland** [comment] 2023-11-14 12:39
So with the update of locode-db can this issue be closed?

**Comment by roman-khimov** [comment] 2023-11-14 12:48
I think so, current DB is at least somewhat consistent wrt this. Data problems are tracked in nspcc-dev/locode-db#25 and will be fixed with another locode-db update.

**Closed** 2023-11-14 12:50 UTC
Labels: bug
