### ISSUE TITLE
password are handled unsecurely

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1297] opened 2022-04-05 14:28 UTC
```
% echo | ../../neofs-cli --rpc-endpoint node1.local:8080 -w client-wallet.json object get --cid hJb4DHbrS6JFrGNUPV4nE4wmtuY1fgJqG5A5gFhUHRW --oid 3QNdaKqtAMy4Pki1Eth2TG4VmbuEZtJ3hjyg6dw6Tk85
get private key: invalid password for the encrypted key
```
```
% ../../neofs-cli --rpc-endpoint node1.local:8080 -w client-wallet.json object get --cid hJb4DHbrS6JFrGNUPV4nE4wmtuY1fgJqG5A5gFhUHRW --oid 3QNdaKqtAMy4Pki1Eth2TG4VmbuEZtJ3hjyg6dw6Tk85 | md5sum 
```

**Comment by fyrchik** [comment] 2022-04-06 07:14
Could you explain what the problem is?

**Comment by 532910** [comment] 2022-04-06 15:25
The simple answer is that the both command just doesn't work.
Passwords should be handled directly via /dev/tty, bypassing standard inputs
https://lists.gnupg.org/pipermail/gnupg-devel/2017-August/032987.html

**Comment by cthulhu-rider** [comment] 2022-04-21 10:49
Portability issues can raise. We need to consider support in Windows.

**Comment by fyrchik** [comment] 2022-06-02 11:35
After the neo-go update we just need to check if it works and if the proper code is used in all cli commands (unify the behaviour).

**Comment by notimetoname** [comment] 2023-05-30 20:47
@roman-khimov, @AnnaShaleva, I've learnt some interesting information about Windows today. It was fun, also, some interesting historical facts appeared and I've become better, faster, stronger.
Anything fun always ends with some unfun things. We already [using](https://github.com/nspcc-dev/neofs-node/blob/ebd0631b73ed7003f514d7088f90561b550f706e/cmd/neofs-cli/internal/key/wallet.go#L69) neo-go's `ReadPassword` and neo-go version is high enough to use `/dev/tty`. Nothing should be done if the task is "do it like neo-go".
On the other hand, I also learned that Windows also has something that _may_ be working: `CONIN$` and `CONOUT$` which _should_ work the same as `/dev/tty` in *unix. I almost started testing it on windows but then... (see above).
So the question, do we want to -- at least -- try it out, or the existing Windows way is good enough for us?

**Comment by roman-khimov** [comment] 2023-05-31 06:00
1. Use the code we have as is now.
2. Open an issue for NeoGo to explore some better ways.

**Comment by notimetoname** [comment] 2023-06-05 11:03
Closing as done for *nix. https://github.com/nspcc-dev/neo-go/issues/3033 as an even better improvement has been opened.

**Closed by notimetoname** 2023-06-05 11:03 UTC
Labels: good first issue
