### ISSUE TITLE
Sync expiration epoch handling

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1674] opened 2022-08-09 16:04 UTC
API [says](https://github.com/nspcc-dev/neofs-api/blob/4de2570e1a3dfc9633bbf02daf74753e7ba46b69/storagegroup/types.proto#L29), [says](https://github.com/nspcc-dev/neofs-api/blob/4de2570e1a3dfc9633bbf02daf74753e7ba46b69/object/types.proto#L123), etc that "expiration epoch" is the _last_ epoch of an entity. It means that an entity must be still valid for that epoch.

Sync implementation and API (session, bearer, TS, SG, etc).

**Comment by realloc** [comment] 2022-08-10 05:40
Isn't it a rephrased duplicate of #1670?

**Comment by carpawell** [comment] 2022-08-10 07:18
@realloc, #1670 is about an object expiration. It _seems_ like implementations in that repo have a totally different understanding of expiration epoch. Not only objects expire wrong but also _every_ entity that has an expiration.

The solution for that issue is syncing all such places.

p.s. removed "object" in that issue description.

**Closed** 2022-09-12 15:57 UTC
Labels: bug, P2, 2022Q4
